#!/bin/bash

#wget https://selenium-release.storage.googleapis.com/4.0/selenium-server-standalone-4.0.0-alpha-2.jar
#curl -O https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar

#java -jar selenium-server-standalone-3.141.59.jar -port 4445
